-- A color scheme that uses native terminal colors
vim.opt.termguicolors = false

local highlights = {
  Search = { ctermbg = 'Yellow', ctermfg = 'Black' },
  IncSearch = { ctermbg = 'Yellow', ctermfg = 'Black' },
  Visual = { ctermbg = 'Yellow', ctermfg = 'Black' },
  LineNr = { ctermfg = 'Yellow' },
  CursorColumn = { ctermbg = 'DarkGray' },
  StatusLine = { ctermbg = 'Yellow', ctermfg = 'Black' },
  StatusLineNC = { ctermbg = 'DarkGray', ctermfg = 'White' },
  Cursor = { ctermbg = 'White', ctermfg = 'Black' },
  ['@annotation'] = { ctermfg = 'Blue' },
  ['@attribute'] = { ctermfg = 'Blue' },
  ['@boolean'] = { ctermfg = 'Red' },
  ['@character'] = { ctermfg = 'Green' },
  ['@character.special'] = { ctermfg = 'LightGreen' },
  ['@comment'] = { ctermfg = 'DarkGray', italic = true },
  ['@comment.documentation'] = { ctermfg = 'DarkGray', italic = true },
  ['@conditional'] = { ctermfg = 'Blue', bold = true },
  ['@repeat'] = { ctermfg = 'Blue', bold = true },
  ['@exception'] = { ctermfg = 'Blue' },
  ['@keyword'] = { ctermfg = 'Blue' },
  ['@keyword.function'] = { ctermfg = 'Blue' },
  ['@keyword.operator'] = { ctermfg = 'Blue' },
  ['@keyword.return'] = { ctermfg = 'Blue' },
  ['@constant'] = { ctermfg = 'Magenta' },
  ['@constant.builtin'] = { ctermfg = 'Magenta' },
  ['@constant.macro'] = { ctermfg = 'Magenta' },
  ['@variable'] = { ctermfg = 'White' },
  ['@variable.builtin'] = { ctermfg = 'Yellow' },
  ['@parameter'] = { ctermfg = 'White' },
  ['@parameter.reference'] = { ctermfg = 'White' },
  ['@function'] = { ctermfg = 'Red' },
  ['@function.builtin'] = { ctermfg = 'Red', bold = true },
  ['@function.call'] = { ctermfg = 'Red' },
  ['@function.macro'] = { ctermfg = 'Red', bold = true },
  ['@method'] = { ctermfg = 'Red' },
  ['@method.call'] = { ctermfg = 'Red' },
  ['@constructor'] = { ctermfg = 'Yellow' },
  ['@type'] = { ctermfg = 'Yellow' },
  ['@type.builtin'] = { ctermfg = 'Yellow' },
  ['@type.definition'] = { ctermfg = 'Yellow' },
  ['@type.qualifier'] = { ctermfg = 'Blue' },
  ['@namespace'] = { ctermfg = 'Yellow' },
  ['@storageclass'] = { ctermfg = 'Blue' },
  ['@property'] = { ctermfg = 'Cyan' },
  ['@field'] = { ctermfg = 'Cyan' },
  ['@string'] = { ctermfg = 'Green' },
  ['@string.escape'] = { ctermfg = 'LightGreen', bold = true },
  ['@string.regex'] = { ctermfg = 'Green' },
  ['@string.special'] = { ctermfg = 'LightGreen' },
  ['@number'] = { ctermfg = 'Cyan' },
  ['@float'] = { ctermfg = 'Cyan' },
  ['@operator'] = { ctermfg = 'White' },
  ['@punctuation.bracket'] = { ctermfg = 'White' },
  ['@punctuation.delimiter'] = { ctermfg = 'White' },
  ['@punctuation.special'] = { ctermfg = 'LightGreen' },
  ['@symbol'] = { ctermfg = 'Magenta' },
  ['@label'] = { ctermfg = 'Yellow' },
  ['@include'] = { ctermfg = 'Blue', italic = true },
  ['@define'] = { ctermfg = 'Blue' },
  ['@debug'] = { ctermfg = 'LightRed' },
  ['@error'] = { ctermfg = 'LightRed' },
  ['@tag'] = { ctermfg = 'Blue' },
  ['@tag.attribute'] = { ctermfg = 'Cyan' },
  ['@tag.delimiter'] = { ctermfg = 'White' },
  ['@text'] = { ctermfg = 'White' },
  ['@text.strong'] = { ctermfg = 'White', bold = true },
  ['@text.emphasis'] = { ctermfg = 'White', italic = true },
  ['@text.underline'] = { ctermfg = 'White', underline = true },
  ['@text.strike'] = { ctermfg = 'White', strikethrough = true },
  ['@text.title'] = { ctermfg = 'Blue', bold = true },
  ['@text.literal'] = { ctermfg = 'Green' },
  ['@text.uri'] = { ctermfg = 'LightGreen', underline = true },
  ['@text.math'] = { ctermfg = 'Cyan' },
  ['@text.environment'] = { ctermfg = 'Blue' },
  ['@text.environment.name'] = { ctermfg = 'Yellow' },
  ['@text.reference'] = { ctermfg = 'Cyan' },
  ['@text.todo'] = { ctermfg = 'DarkGray', bold = true },
  ['@text.note'] = { ctermfg = 'LightBlue', bold = true },
  ['@text.warning'] = { ctermfg = 'LightYellow', bold = true },
  ['@text.danger'] = { ctermfg = 'LightRed', bold = true },
  ['@variable.builtin.vim'] = { ctermfg = 'Yellow' },
  ['@function.builtin.vim'] = { ctermfg = 'Red' },
  ['@tag.html'] = { ctermfg = 'Blue' },
  ['@tag.delimiter.html'] = { ctermfg = 'White' },
  ['@tag.attribute.html'] = { ctermfg = 'Cyan' },
  ['@property.css'] = { ctermfg = 'Cyan' },
  ['@type.css'] = { ctermfg = 'Blue' },
  ['@string.css'] = { ctermfg = 'Green' },
  ['@number.css'] = { ctermfg = 'Cyan' },
  ['@constructor.javascript'] = { ctermfg = 'Yellow' },
  ['@constructor.typescript'] = { ctermfg = 'Yellow' },
  ['@variable.builtin.javascript'] = { ctermfg = 'Yellow' },
  ['@variable.builtin.typescript'] = { ctermfg = 'Yellow' },
  BlinkCmpMenu = { ctermfg = 'White', ctermbg = 'Black' },
  BlinkCmpMenuBorder = { ctermfg = 'Black' },
  BlinkCmpMenuSelection = { ctermfg = 'White', ctermbg = 'Black' },
  BlinkCmpMenuSearchMatch = { ctermfg = 'Black', ctermbg = 'Yellow' },
  BlinkCmpLabel = { ctermfg = 'White' },
  BlinkCmpLabelDetail = { ctermfg = 'Black' },
  BlinkCmpLabelDescription = { ctermfg = 'Black', italic = true },
  BlinkCmpLabelMatch = { ctermfg = 'Red', bold = true },
  BlinkCmpLabelDeprecated = { ctermfg = 'Black', strikethrough = true },
  BlinkCmpSignature = { ctermfg = 'White', ctermbg = 'Black' },
  BlinkCmpSignatureBorder = { ctermfg = 'Black', ctermbg = 'Black' },
  BlinkCmpSignatureActiveParameter = { ctermfg = 'Red', ctermbg = 'Black' },
  BlinkCmpScrollbar = { ctermfg = 'Black', ctermbg = 'Black' },
  BlinkCmpScrollbarThumb = { ctermfg = 'White', ctermbg = 'Black' },
  BlinkCmpDoc = { ctermfg = 'White', ctermbg = 'Black' },
  BlinkCmpDocBorder = { ctermfg = 'Black' },
  BlinkCmpDocSeparator = { ctermfg = 'Black' },
  BlinkCmpGhostText = { ctermfg = 'Black', italic = true },
  BlinkCmpFuzzy = { ctermfg = 'Red', bold = true },
  BlinkCmpFuzzyMatch = { ctermfg = 'Black', ctermbg = 'Yellow' },
  BlinkCmpPreview = { ctermfg = 'White', ctermbg = 'Black' },
  BlinkCmpPreviewBorder = { ctermfg = 'Black' },
  BlinkCmpPreviewTitle = { ctermfg = 'Red', bold = true },
  MasonNormal = { ctermfg = 'White' },
  MasonHeader = { ctermfg = 'Red', bold = true },
  MasonHeaderSecondary = { ctermfg = 'Cyan', bold = true },
  MasonHighlight = { ctermfg = 'Red' },
  MasonHighlightSecondary = { ctermfg = 'Cyan' },
  MasonError = { ctermfg = 'Red' },
  MasonWarning = { ctermfg = 'Yellow' },
  MasonInfo = { ctermfg = 'Blue' },
  MasonMuted = { ctermfg = 'Black' },
  MasonPackageInstalled = { ctermfg = 'Blue' },
  MasonPackagePending = { ctermfg = 'Yellow' },
  MasonPackageUninstalled = { ctermfg = 'Red' },
  MasonHeading = { ctermfg = 'Red', bold = true },
  MasonHint = { ctermfg = 'Cyan' },
  MasonProgress = { ctermfg = 'Red' },
  MasonDir = { ctermfg = 'Yellow' },
  MasonFile = { ctermfg = 'Green' },
  MasonPackageOutdated = { ctermfg = 'Black' },
  MasonButton = { ctermfg = 'Black', ctermbg = 'Red' },
  MasonButtonSecondary = { ctermfg = 'Black', ctermbg = 'Cyan' },
  MasonLogInfo = { ctermfg = 'Blue' },
  MasonLogWarn = { ctermfg = 'Yellow' },
  MasonLogError = { ctermfg = 'Red' },
  MasonLogDebug = { ctermfg = 'Black' },
  MasonLogTrace = { ctermfg = 'Black' },
  MasonInstallSuccess = { ctermfg = 'Blue' },
  MasonInstallFailed = { ctermfg = 'Red' },
  MasonInstallPending = { ctermfg = 'Yellow' },
  MasonUninstallSuccess = { ctermfg = 'Blue' },
  MasonUninstallFailed = { ctermfg = 'Red' },
  MasonUninstallPending = { ctermfg = 'Yellow' },
  MasonUpdateSuccess = { ctermfg = 'Blue' },
  MasonUpdateFailed = { ctermfg = 'Red' },
  MasonUpdatePending = { ctermfg = 'Yellow' },
  MasonSource = { ctermfg = 'Black' },
  MasonVersion = { ctermfg = 'Cyan' },
  MasonLanguage = { ctermfg = 'Yellow' },
  MasonCategory = { ctermfg = 'Blue' },
  MasonDescription = { ctermfg = 'Black', italic = true },
  MasonHomepage = { ctermfg = 'Blue', underline = true },
  MasonLicense = { ctermfg = 'Black' },
  MasonSize = { ctermfg = 'Cyan' },
  MasonDate = { ctermfg = 'Black' },
  MasonCount = { ctermfg = 'Cyan', bold = true },
  MasonSeparator = { ctermfg = 'Black' },
  MasonSpinner = { ctermfg = 'Red' },
  MasonCheckmark = { ctermfg = 'Blue' },
  MasonCross = { ctermfg = 'Red' },
  MasonDash = { ctermfg = 'Black' },
  MasonArrow = { ctermfg = 'Red' },
  MasonBorder = { ctermfg = 'Black' },
  MasonTitle = { ctermfg = 'Red', bold = true },
  MasonSubtitle = { ctermfg = 'Cyan' },
  MasonText = { ctermfg = 'White' },
  MasonHelp = { ctermfg = 'Black', italic = true },
  MasonToggle = { ctermfg = 'Blue' },
  MasonFilter = { ctermfg = 'Red' },
  MasonSearch = { ctermfg = 'Black', ctermbg = 'Yellow' },
  MasonMatch = { ctermfg = 'Red', bold = true },
  MasonPrompt = { ctermfg = 'Blue', bold = true },
  MasonCursor = { ctermfg = 'Black', ctermbg = 'White' },
  MasonVirtualText = { ctermfg = 'Black', italic = true },
}

for group, opts in pairs(highlights) do
  vim.api.nvim_set_hl(0, group, opts)
end
